export const menuStructure_FR = {
    "Emplois et milieu de travail": {
      url: "https://www.canada.ca/fr/services/emplois.html",
      submenus: {
        "Trouver un emploi": "https://www.canada.ca/fr/services/emplois/opportunites.html",
        "Financement pour les emplois et formations": "https://www.canada.ca/fr/emploi-developpement-social/services/financement/programmes.html",
        "Formation": "https://www.canada.ca/fr/services/emplois/formation.html",
        "Embauche et gestion de personnel": "https://www.canada.ca/gestion-entreprise",
        "Démarrage d'entreprise": "https://www.canada.ca/demarrage-entreprise",
        "Normes en milieu de travail": "https://www.canada.ca/fr/services/emplois/milieu-travail.html",
        "Prestations d'assurance-emploi et congés": "https://www.canada.ca/fr/services/prestations/ae.html",
        "Pensions et retraite": "https://www.canada.ca/fr/services/finance/pensions.html",
      },
      mostRequested: {
        "Recherche d'emplois ou d'apprentissages - Guichet Emplois": "https://www.guichetemplois.gc.ca/accueil",
        "Travailler au Canada": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/travailler-canada.html",
        "Immigrer en tant que travailleur qualifié": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/immigrer-canada/entree-express.html",
        "Embaucher un travailleur étranger temporaire": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/travailler-canada/embaucher-etranger-temporaires.html",
        "Voir vos relevés d'emploi": "https://www.canada.ca/fr/emploi-developpement-social/services/mon-dossier.html",
        "Soumettre des relevés d'emploi en ligne - employeurs": "https://www.canada.ca/fr/emploi-developpement-social/programmes/assurance-emploi/ae-liste/assurance-emploi-re/acceder-re.html",
        "Demander un numéro d'assurance-sociale": "https://www.canada.ca/fr/emploi-developpement-social/services/numero-assurance-sociale.html",
      }
    },
    "Immigration et citoyenneté": {
      url: "https://www.canada.ca/fr/services/immigration-citoyennete.html",
      submenus: {
        "Ma demande": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/demande.html",
        "Visiter": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/visiter-canada.html",
        "Immigrer": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/immigrer-canada.html",
        "Travailler": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/travailler-canada.html",
        "Étudier": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/etudier-canada.html",
        "Citoyenneté": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/citoyennete-canadienne.html",
        "Nouveaux immigrants": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/nouveaux-immigrants.html",
        "Canadiens": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/canadiens.html",
        "Réfugiés et octroi de l'asile": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/refugies.html",
        "Application de la loi et infractions": "https://www.canada.ca/fr/services/immigration-citoyennete/application-loi-infractions.html",
      },
      mostRequested: {
        "Se connecter à un compte IRCC": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/demande/comptes-ircc.html",
        "Vérifier l'état de sa demande": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/demande/verifier-etat.html",
        "Vérifier les délais de traitement des demandes": "https://ircc.canada.ca/francais/information/delais/index.asp",
        "Trouver un formulaire de demande": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/demande/formulaires-demande-guides.html",
        "Payer les frais": "https://ircc.canada.ca/francais/information/frais/index.asp",
        "Déterminer si vous avez besoin d'une AVE ou d'un visa pour visiter le Canada": "https://ircc.canada.ca/francais/visiter/visas.asp",
        "Trouver réponse à ses questions dans le Centre d'aide": "https://ircc.canada.ca/francais/centre-aide/index-en-vedette-can.asp",
      }
    },
    "Voyage et tourisme": {
      url: "https://voyage.gc.ca/",
      submenus: {
        "Conseils aux voyageurs et avertissements": "https://voyage.gc.ca/voyager/avertissements",
        "COVID-19 : voyage, dépistage et frontières": "https://voyage.gc.ca/voyage-covid",
        "Visiter le Canada": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/visiter-canada.html?outside",
        "Voyager à l'étranger": "https://voyage.gc.ca/voyager",
        "Voyager en avion": "https://voyage.gc.ca/avion",
        "Retour au Canada": "https://voyage.gc.ca/retour",
        "Passeports et documents de voyage canadiens": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/passeports-canadiens.html",
        "Attraits touristiques, événements et expériences au Canada": "https://voyage.gc.ca/tourisme-canadien",
        "Assistance à l'extérieur du Canada": "https://voyage.gc.ca/assistance",
        "Restez branchés": "https://voyage.gc.ca/restez-branches",
      },
      mostRequested: {
        "Assistance d'urgence à l'étranger": "https://voyage.gc.ca/assistance/assistance-d-urgence",
        "Vérifiez si vous avez besoin d'un visa pour voyager au Canada": "https://ircc.canada.ca/francais/visiter/visas.asp",
        "Présentez une demande d'Autorisation de voyage électronique (AVE)": "https://www.canada.ca/fr/immigration-refugies-citoyennete/services/visiter-canada/ave.html",
        "Adhérez à NEXUS": "https://www.cbsa-asfc.gc.ca/services/travel-voyage/prog/nexus/menu-fra.html",
        "Inscrivez-vous comme Canadien à l'étranger": "https://voyage.gc.ca/voyager/inscription",
        "Assurance voyage": "https://voyage.gc.ca/voyager/documents/assurance-voyage",
      }
    },
    "Entreprises et industrie": {
      url: "https://www.canada.ca/fr/services/entreprises.html",
      submenus: {
        "Démarrage d'entreprise": "https://www.canada.ca/fr/services/entreprises/lancer.html",
        "Subventions et financement pour les entreprises": "https://www.canada.ca/fr/services/entreprises/subventions.html",
        "Taxes et impôt des entreprises": "https://www.canada.ca/fr/services/entreprises/impots.html",
        "Sociétés de régime fédéral": "https://www.canada.ca/fr/services/entreprises/societes-de-regime-federal.html",
        "Embauche et gestion de personnel": "https://www.canada.ca/fr/services/entreprises/engager.html",
        "Commerce international et investissements": "https://international.canada.ca/fr/services/entreprises/commerce",
        "Permis, licences et règlements": "https://www.canada.ca/fr/services/entreprises/permis.html",
        "Faire affaire avec le gouvernement": "https://www.canada.ca/fr/services/entreprises/faire-affaire.html",
        "Recherche-développement et innovation": "https://www.canada.ca/fr/services/science/innovation.html",
        "Recherche et renseignements d'affaires": "https://www.canada.ca/fr/services/entreprises/recherche.html",
        "Propriété intellectuelle et droit d'auteur": "https://www.canada.ca/fr/services/entreprises/pi.html",
        "Administration de votre entreprise": "https://www.canada.ca/fr/services/entreprises/maintenirfairecroitreameliorerentreprise.html",
        "Protection de votre entreprise": "https://www.canada.ca/fr/services/entreprises/proteger.html",
        "Insolvabilité pour les entreprises": "https://www.canada.ca/fr/services/entreprises/faillites.html",
      },
      mostRequested: {
        "Trouver une société": "https://ised-isde.canada.ca/cc/lgcy/fdrlCrpSrch.html?lang=fra",
        "Déclarer vos produits importés": "https://www.cbsa-asfc.gc.ca/prog/manif/portal-portail-fra.html",
        "Chercher des marques de commerce": "https://ised-isde.canada.ca/opic/recherche-marques/srch?null=&lang=fre",
        "Réviser les tarifs des douanes pour l'importation de produits": "https://www.cbsa-asfc.gc.ca/trade-commerce/tariff-tarif/2018/html/tblmod-1-fra.html",
        "Trouver un brevet": "https://www.ic.gc.ca/opic-cipo/cpd/fra/introduction.html",
        "Importer et exporter à partir du Canada": "https://www.cbsa-asfc.gc.ca/comm-fra.html",
        "Trouver un nom pour votre compagnie": "https://ic.gc.ca/eic/site/cd-dgc.nsf/fra/h_cs03922.html",
        "Apporter des changements à votre société (Centre de dépôt en ligne)": "https://ised-isde.canada.ca/cc/lgcy/hm.html?locale=fr_CA",
      }
    },
        "Prestations": {
          url: "https://www.canada.ca/fr/services/prestations.html",
          submenus: {
            "Prestations d'assurance-emploi et congés": "https://www.canada.ca/fr/services/prestations/ae.html",
            "Couverture dentaire": "https://www.canada.ca/fr/services/prestations/dentaire/regime-soins-dentaires.html",
            "Prestations pour les familles et les proches aidants": "https://www.canada.ca/fr/services/prestations/famille.html",
            "Pensions publiques": "https://www.canada.ca/fr/services/prestations/pensionspubliques.html",
            "Subventions et occasions de financement": "https://www.canada.ca/fr/emploi-developpement-social/services/financement/programmes.html",
            "Aide financière aux étudiants et planification des études": "https://www.canada.ca/fr/services/prestations/etudes.html",
            "Prestations relatives au logement": "https://www.canada.ca/fr/services/prestations/logement.html",
            "Prestations d'invalidité": "https://www.canada.ca/fr/services/prestations/handicap.html",
            "Prestations par clientèle": "http://www.canada.ca/fr/services/prestations/clientele.html",
            "Dates de paiement des prestations": "https://www.canada.ca/fr/services/prestations/calendrier.html",
            "Chercheur de prestations": "https://benefitsfinder.services.gc.ca/hm?GoCTemplateCulture=fr-CA&cl=true",
            "Aviser le gouvernement d'un décès": "https://www.canada.ca/fr/services/prestations/aviser-gouvernement-deces.html",
          },
          mostRequested: {
            "Présenter une demande d'assurance-emploi": "https://www.canada.ca/fr/services/prestations/ae/assurance-emploi-reguliere.html",
            "Faire une demande de bourses et de prêts d'études": "https://www.canada.ca/fr/services/prestations/education/aide-etudiants/bourses-prets.html",
            "Ouvrir une session pour un compte en ligne du gouvernement du Canada": "https://www.canada.ca/fr/gouvernement/ouvrir-session-dossier-compte-en-ligne.html",
            "S'inscrire ou modifier vos informations de dépôt direct": "https://www.canada.ca/fr/services-publics-approvisionnement/services/paiements-vers-depuis-gouvernement/depot-direct.html",
            "Calculateur de prestations pour enfants et familles": "https://www.canada.ca/fr/agence-revenu/services/prestations-enfants-familles/calculateur-prestations-enfants-familles.html",
            "Soumettre une déclaration d'assurance-emploi": "https://www.canada.ca/fr/services/prestations/ae/assurance-emploi-declaration-internet.html",
          }
        },
        "Santé": {
          url: "https://www.canada.ca/fr/services/sante.html",
          submenus: {
            "Aliments et nutrition": "https://www.canada.ca/fr/services/sante/aliments-et-nutrition.html",
            "Maladies et affections": "https://www.canada.ca/fr/sante-publique/services/maladies.html",
            "Vaccins et immunisation": "https://www.canada.ca/fr/sante-publique/sujets/immunisation-et-vaccins.html",
            "Médicaments et produits de santé": "https://www.canada.ca/fr/services/sante/medicaments-et-produits-sante.html",
            "Sécurité des produits": "https://www.canada.ca/fr/services/sante/securite-produits.html",
            "Sécurité et risque pour la santé": "https://www.canada.ca/fr/services/sante/securite-et-risque-pour-sante.html",
            "Vie saine": "https://www.canada.ca/fr/services/sante/vie-saine.html",
            "Santé des Autochtones": "https://www.canada.ca/fr/services/sante/sante-autochtones.html",
            "Système et services de santé": "https://www.canada.ca/fr/services/sante/systeme-et-services-sante.html",
            "Science, recherche et données": "https://www.canada.ca/fr/services/sante/science-recherche-et-donnees.html",
          },
          mostRequested: {
            "Guide alimentaire Canada": "https://guide-alimentaire.canada.ca/fr/",
            "Rappels et avis de sécurité": "https://recalls-rappels.canada.ca/fr",
            "Soutien en santé mentale : Demander de l'aide": "https://www.canada.ca/fr/sante-publique/services/services-sante-mentale/sante-mentale-obtenir-aide.html",
            "Rougeole": "https://www.canada.ca/fr/sante-publique/services/maladies/rougeole.html",
          }
        },
        "Impôts": {
          url: "https://www.canada.ca/fr/services/impots.html",
          submenus: {
            "Impôt sur le revenu": "https://www.canada.ca/fr/services/impots/impot-sur-le-revenu.html",
            "TPS/TVH": "https://www.canada.ca/fr/agence-revenu/services/impot/entreprises/sujets/tps-tvh-entreprises.html",
            "Retenues sur la paie": "https://www.canada.ca/fr/agence-revenu/services/impot/entreprises/sujets/retenues-paie.html",
            "Numéro d'entreprise": "https://www.canada.ca/fr/services/impots/numero-dentreprise.html",
            "Régimes d'épargne et de pension": "https://www.canada.ca/fr/services/impots/regimes-depargne-et-de-pension.html",
            "Crédits d'impôt et prestations pour les particuliers": "https://www.canada.ca/fr/services/impots/prestations-pour-enfants-et-familles.html",
            "Taxes d'accise, droits et prélèvements": "https://www.canada.ca/fr/services/impots/taxes-daccise-droits-et-prelevements.html",
            "Organismes de bienfaisance et dons": "https://www.canada.ca/fr/services/impots/bienfaisance.html",
          },
          mostRequested: {
            "Mon dossier": "https://www.canada.ca/fr/agence-revenu/services/services-electroniques/services-numeriques-particuliers/dossier-particuliers.html",
            "Mon dossier d'entreprise": "https://www.canada.ca/fr/agence-revenu/services/services-electroniques/services-numeriques-entreprises/dossier-entreprise.html",
            "Représenter un client": "https://www.canada.ca/fr/agence-revenu/services/services-electroniques/representer-client.html",
            "Transmettre une déclaration de TPS/TVH (IMPÔTNET)": "https://www.canada.ca/fr/agence-revenu/services/services-electroniques/services-numeriques-entreprises/impotnet-tps-tvh.html",
            "Faire un paiement à l'Agence du revenu du Canada": "https://www.canada.ca/fr/agence-revenu/services/faire-paiement-a-agence-revenu-canada.html",
            "Trouver la date du prochain versement des prestations": "https://www.canada.ca/fr/agence-revenu/services/prestations-enfants-familles/dates-versement-prestations.html",
          }
        },
        "Environnement et ressources naturelles": {
          url: "https://www.canada.ca/fr/services/environnement.html",
          submenus: {
            "Météo, climat et catastrophes naturelles": "https://www.canada.ca/fr/services/environnement/meteo.html",
            "Énergie": "https://www.canada.ca/fr/services/environnement/energie.html",
            "Ressources naturelles": "https://www.canada.ca/fr/services/environnement/ressources-naturelles.html",
            "Agriculture": "https://agriculture.canada.ca/fr",
            "Pêches": "https://www.canada.ca/fr/services/environnement/peches.html",
            "Faune, flore et espèces": "https://www.canada.ca/fr/services/environnement/faune-flore-especes.html",
            "Pollution et gestion des déchets": "https://www.canada.ca/fr/services/environnement/pollution-gestion-dechets.html",
            "Conservation et protection de l'environnement": "https://www.canada.ca/fr/services/environnement/conservation.html",
          },
          mostRequested: {
            "Prévisions météo locales": "https://meteo.gc.ca/canada_f.html",
            "Véhicules écoénergétiques": "https://www.rncan.gc.ca/energie/efficacite/transports/20997",
            "Efficacité énergétique des maisons": "https://www.rncan.gc.ca/maisons",
            "Espèces en péril": "https://www.canada.ca/fr/environnement-changement-climatique/services/registre-public-especes-peril.html",
            "Préparation aux conditions météorologiques dangereuses": "https://www.canada.ca/fr/environnement-changement-climatique/services/meteo-saisonniere-dangereuse.html",
          }
        },
            "Sécurité nationale et défense": {
              url: "https://www.canada.ca/fr/services/defense.html",
              submenus: {
                "Sécurité nationale": "https://www.canada.ca/fr/services/defense/securitenationale.html",
                "Forces armées canadiennes": "https://www.canada.ca/fr/services/defense/fac.html",
                "Achat et mise à niveau d'équipement de la Défense": "https://www.canada.ca/fr/services/defense/achat-mise-a-niveau-equipement-defense.html",
                "Sûreté des transports": "https://tc.canada.ca/fr/services-generaux/surete-transports",
                "Sécuriser la frontière": "https://www.canada.ca/fr/services/defense/securiserfrontiere.html",
                "Cybersécurité": "https://www.canada.ca/fr/services/defense/cybersecurite.html",
                "Emplois en sécurité nationale et en défense": "https://www.canada.ca/fr/services/defense/emplois.html",
                "Services et avantages sociaux du personnel militaire": "https://www.canada.ca/fr/gouvernement/fonctionpublique/avantagesmilitaires.html",
              },
              mostRequested: {
                "Emplois dans les Forces armées canadiennes": "https://forces.ca/fr/carrieres/",
                "Grades militaires": "https://www.canada.ca/fr/ministere-defense-nationale/services/histoire-militaire/histoire-patrimoine/insignes-drapeaux/grades/insignes-grade-fonction.html",
                "Équipement de la Défense": "https://www.canada.ca/fr/services/defense/fac/equipement.html",
                "Joignez-vous aux cadets": "https://www.canada.ca/fr/ministere-defense-nationale/services/cadets-rangers-juniors-canadiens/cadets/rejoignez-nous.html",
                "Politique de défense du Canada": "http://dgpaapp.forces.gc.ca/fr/politique-defense-canada/index.asp",
              }
            },
            "Culture, histoire et sport": {
              url: "https://www.canada.ca/fr/services/culture.html",
              submenus: {
                "Financement - Culture, histoire et sport": "https://www.canada.ca/fr/patrimoine-canadien/services/financement.html",
                "Événements, célébrations et commémorations": "https://www.canada.ca/fr/services/culture/evenements-celebrations-commemorations.html",
                "Lieux et attraits culturels": "https://www.canada.ca/fr/services/culture/attraits-culturels.html",
                "Identité canadienne et société": "https://www.canada.ca/fr/services/culture/identite-canadienne-societe.html",
                "Sport": "https://www.canada.ca/fr/services/culture/sport.html",
                "Histoire et patrimoine": "https://www.canada.ca/fr/services/culture/histoire-patrimoine.html",
                "Arts et média": "https://www.canada.ca/fr/services/culture/arts-media.html",
                "Programmes culturels pour les jeunes": "https://www.canada.ca/fr/services/culture/programmes-culturels-jeunes.html",
                "Commerce et investissement culturels": "https://www.canada.ca/fr/services/culture/commerce-investissement-culturels.html",
              },
              mostRequested: {
                "Visitez le Mémorial virtuel de guerre du Canada": "https://www.veterans.gc.ca/fra/remembrance/memorials/canadian-virtual-war-memorial",
                "Hymnes et symboles du Canada": "https://www.canada.ca/fr/services/culture/identite-canadienne-societe/hymnes-symboles.html",
                "Trouvez une décision du CRTC": "https://crtc.gc.ca/fra/8045/d2018.htm",
                "Faites des recherches sur votre histoire familiale": "https://bibliotheque-archives.canada.ca/fra/collection/aide-recherche/genealogie-histoire-famille/Pages/genealogie-histoire-famille.aspx",
                "Cherchez des documents de recensement": "https://bibliotheque-archives.canada.ca/fra/collection/aide-recherche/genealogie-histoire-famille/recensements/Pages/recensements.aspx",
                "Lieux et attraits dans la capitale du Canada": "https://www.canada.ca/fr/services/culture/attraits-culturels/attraits-capitale-canada.html",
              }
            },
            "Services de police, justice et urgences": {
              url: "https://www.canada.ca/fr/services/police.html",
              submenus: {
                "Services de police": "https://www.canada.ca/fr/services/police/servicespolice.html",
                "Justice": "https://www.canada.ca/fr/services/police/justice.html",
                "Urgences": "https://www.canada.ca/fr/services/police/urgences.html",
                "Services correctionnels": "https://www.canada.ca/fr/services/police/correctionnels.html",
                "Libération conditionnelle, suspension du casier, radiation et clémence": "https://www.canada.ca/fr/services/police/liberationconditionnelle.html",
                "Victimes d'actes criminels": "https://www.canada.ca/fr/services/police/victimes.html",
              },
              mostRequested: {
                "Demander ou renouveler un permis d'arme à feu": "http://www.rcmp-grc.gc.ca/cfp-pcaf/online_en-ligne/index-fra.htm",
                "Obtenir une attestation de vérification de casier judiciaire": "http://www.rcmp-grc.gc.ca/fr/verification-casier-judiciaire",
                "Demander la suspension d'un casier judiciaire": "https://www.canada.ca/fr/commission-liberations-conditionnelles/services/suspension-du-casier/guide-et-formulaires-de-demande.html",
                "Que faire durant une urgence": "https://www.preparez-vous.gc.ca/cnt/hzd/drng-fr.aspx",
                "Connaissez la loi sur la conduite avec facultés affaiblies": "https://www.canada.ca/fr/services/police/servicespolice/securite-communautaire-police/conduite-facultes-affaiblies.html",
                "Aidez à résoudre un crime": "https://www.canada.ca/fr/services/police/servicespolice/aider-resoudre-un-crime.html",
              }
            },
            "Transport et infrastructure": {
              url: "https://www.canada.ca/fr/services/transport.html",
              submenus: {
                "Aviation": "https://tc.canada.ca/fr/aviation",
                "Transport maritime": "https://tc.canada.ca/fr/transport-maritime",
                "Transport routier": "https://tc.canada.ca/fr/transport-routier",
                "Transport ferroviaire": "https://tc.canada.ca/fr/transport-ferroviaire",
                "Marchandises dangereuses": "https://tc.canada.ca/fr/marchandises-dangereuses",
                "Infrastructure": "https://tc.canada.ca/fr/services/infrastructures.html",
              },
              mostRequested: {
                "Véhicules zéro émission": "https://www.canada.ca/fr/services/transport/vehicules-zero-emission.html",
                "Sécurité des drones": "https://tc.canada.ca/fr/aviation/securite-drones",
                "Articles interdits à bord d'un avion": "https://tc.canada.ca/fr/aviation/surete-aerienne/ce-que-vous-ne-pouvez-pas-apporter-dans-avion",
                "Immatriculer votre bâtiment": "https://tc.canada.ca/fr/transport-maritime/permis-immatriculation-batiments",
                "Sécurité des sièges d'auto pour enfants": "https://tc.canada.ca/fr/transport-routier/securite-sieges-auto-enfants",
                "Transporter des marchandises dangereuses - Règlements": "https://tc.canada.ca/fr/marchandises-dangereuses/table-matieres",
                "Règlement de l'aviation canadien": "https://tc.canada.ca/fr/services-generaux/lois-reglements/liste-reglements/reglement-aviation-canadien-dors-96-433",
              }
            },
                "Canada et le monde": {
                  url: "https://www.international.gc.ca/world-monde/index.aspx?lang=fra",
                  submenus: {
                    "Bureaux internationaux et contacts d'urgence": "https://www.international.gc.ca/world-monde/offices-bureaux/index.aspx?lang=fra",
                    "Étude, travail et voyage partout dans le monde": "https://www.international.gc.ca/world-monde/study_work_travel-etude_travail_voyage/index.aspx?lang=fra",
                    "Information par pays et territoires": "https://www.international.gc.ca/world-monde/country-pays/index.aspx?lang=fra",
                    "Histoires": "https://www.international.gc.ca/world-monde/stories-histoires/index.aspx?lang=fra",
                    "Relations internationales": "https://www.international.gc.ca/world-monde/international_relations-relations_internationales/index.aspx?lang=fra",
                    "Enjeux mondiaux et aide internationale": "https://www.international.gc.ca/world-monde/issues_development-enjeux_developpement/index.aspx?lang=fra",
                    "Financement d'initiatives internationales": "https://www.international.gc.ca/world-monde/funding-financement/index.aspx?lang=fra",
                    "Commerce international et investissements": "https://international.canada.ca/fr/services/entreprises/commerce",
                  },
                  mostRequested: {
                    "Trouver une bourse d'études canadienne en tant qu'étudiant international": "https://www.educanada.ca/scholarships-bourses/non_can/index.aspx?lang=fra",
                    "Traités internationaux signés par le Canada": "https://treaty-accord.gc.ca/index.aspx?Lang=fra",
                    "Trouver des occasions d'étude ou de recherche au Canada": "https://www.educanada.ca/index.aspx?lang=fra",
                    "Communiquer avec une ambassade ou un consulat": "https://voyage.gc.ca/assistance/ambassades-consulats",
                    "Communiquer avec un représentant étranger au Canada": "https://www.international.gc.ca/protocol-protocole/reps.aspx?lang=fra",
                    "Authentifier un document": "https://www.international.gc.ca/gac-amc/about-a_propos/services/authentication-authentification/step-etape-1.aspx?lang=fra",
                  }
                },
                "Argent et finances": {
                  url: "https://www.canada.ca/fr/services/finance.html",
                  submenus: {
                    "Gérer votre argent": "https://www.canada.ca/fr/services/finance/gerer.html",
                    "Dettes et emprunts": "https://www.canada.ca/fr/services/finance/dettes.html",
                    "Épargne et investissement": "https://www.canada.ca/fr/services/finance/epargne.html",
                    "Financement des études": "https://www.canada.ca/fr/services/finance/financementetudes.html",
                    "Pensions et retraite": "https://www.canada.ca/fr/services/finance/pensions.html",
                    "Protection contre la fraude et les escroqueries": "https://www.canada.ca/fr/services/finance/fraude.html",
                    "Calculatrices et outils financiers": "https://www.canada.ca/fr/services/finance/outils.html",
                    "Programmes de littératie financière": "https://www.canada.ca/fr/agence-consommation-matiere-financiere/services/programmes-litteratie-financiere.html",
                    "Questions de consommation": "https://www.canada.ca/fr/services/finance/questions-consommation.html",
                    "Insolvabilité": "https://www.canada.ca/fr/services/finance/faillite.html",
                    "Impôts": "https://www.canada.ca/fr/services/impots.html",
                    "Finances publiques": "https://www.canada.ca/fr/gouvernement/systeme/finances.html",
                    "Subventions et financement pour les entreprises": "https://www.canada.ca/fr/services/entreprises/subventions.html",
                    "Réglementation des services financiers et monétaires": "https://www.canada.ca/fr/services/entreprises/permis/secteursindustriereglementationfederale/regleservicesfinanciers.html",
                  },
                  mostRequested: {
                    "Trouver un dossier de faillite ou d'insolvabilité": "https://www.ic.gc.ca/app/scr/bsf-osb/ins/connexion.html?lang=fra",
                    "Prêts étudiants": "https://www.canada.ca/fr/services/emplois/education/aide-financiere-etudiants/pret-etudiants.html",
                    "S'inscrire ou modifier vos informations de dépôt direct": "https://www.canada.ca/fr/services-publics-approvisionnement/services/paiements-vers-depuis-gouvernement/depot-direct.html",
                    "Obtenir des renseignements sur les hypothèques": "https://www.canada.ca/fr/agence-consommation-matiere-financiere/services/hypotheques.html",
                    "Dossiers et cotes de crédit": "https://www.canada.ca/fr/agence-consommation-matiere-financiere/services/dossier-pointage-credit.html",
                    "Faire un budget": "https://itools-ioutils.fcac-acfc.gc.ca/BP-PB/planificateur-budgetaire",
                    "Taux et limites de contribution": "https://www.canada.ca/fr/agence-revenu/services/impot/administrateurs-regimes-enregistres/fesp/plafonds-cd-reer-rpdb-celi-mgap.html",
                  }
                },
                "Science et innovation": {
                  url: "https://www.canada.ca/fr/services/science.html",
                  submenus: {
                    "Financement, subventions et prix pour la recherche": "https://www.canada.ca/fr/services/science/financementrecherche.html",
                    "Thèmes scientifiques": "https://www.canada.ca/fr/services/science/themesscientifiques.html",
                    "Données ouvertes, statistiques et archives": "https://www.canada.ca/fr/services/science/donnees-ouvertes.html",
                    "Instituts et établissements de recherches": "https://www.canada.ca/fr/services/science/instituts.html",
                    "R-D et innovation": "https://www.canada.ca/fr/services/science/innovation.html",
                    "Propriété intellectuelle et droit d'auteur": "https://www.canada.ca/fr/services/entreprises/pi.html",
                    "Répertoire des scientifiques et des professionnels de la recherche": "https://www.canada.ca/fr/services/science/repertoirescientifiques.html",
                    "Ressources pédagogiques scientifiques": "https://www.canada.ca/fr/services/science/ressourcespedagogiques.html",
                  },
                  mostRequested: {
                    "Code national du bâtiment": "https://cnrc.canada.ca/fr/certifications-evaluations-normes/codes-canada/publications-codes-canada",
                    "Heures officielles au Canada": "https://cnrc.canada.ca/fr/horloge-web/",
                    "Trouver les heures de levers et de couchers du soleil": "https://cnrc.canada.ca/fr/recherche-developpement/produits-services/logiciels-applications/calculatrice-soleil/",
                    "Bourses pour l'innovation technologique (PARI)": "https://cnrc.canada.ca/fr/soutien-linnovation-technologique/soutien-financier-linnovation-technologique-pari-cnrc",
                    "Réseau des bibliothèques scientifiques fédérales": "https://science-libraries.canada.ca/fra/accueil/",
                    "Aurores boréales en direct": "http://asc-csa.gc.ca/fra/astronomie/auroramax/hd-480.asp",
                  }
        },
        "À propos du gouvernement": {
          url: "https://www.canada.ca/fr/gouvernement/systeme.html",
          submenus: {
            "Comment le gouvernement fonctionne": "https://www.canada.ca/fr/gouvernement/systeme/comment-gouvernement-fonctionne.html",
            "Priorités du gouvernement": "https://www.canada.ca/fr/gouvernement/systeme/priorites.html",
            "Traités, lois et règlements": "https://www.canada.ca/fr/gouvernement/systeme/lois.html",
            "Travailler au gouvernement du Canada": "https://www.canada.ca/fr/gouvernement/fonctionpublique.html",
            "Rapports pangouvernementaux sur les dépenses et les activités": "https://www.canada.ca/fr/gouvernement/systeme/rapports-pangouvernementaux-depenses-activites.html",
            "Gouvernement ouvert": "https://open.canada.ca/fr",
            "Faire affaire avec le gouvernement": "https://www.canada.ca/fr/services/entreprises/faire-affaire.html",
            "Politiques, normes, directives et lignes directrices": "https://www.tbs-sct.gc.ca/pol/index-fra.aspx",
            "Biens immobiliers fédéraux": "https://www.canada.ca/fr/gouvernement/systeme/biens.html",
            "Exigences en matière de communications gouvernementales": "https://www.canada.ca/fr/secretariat-conseil-tresor/sujets/communications-gouvernementales.html",
            "Communiquer avec le gouvernement": "https://www.canada.ca/fr/gouvernement/systeme/consultations.html",
            "Gouvernement à l’ère numérique": "https://www.canada.ca/fr/gouvernement/systeme/gouvernement-numerique.html"
          },
          mostRequested: {
            "Nouvelles": "https://www.canada.ca/fr/nouvelles.html",
            "Ministères et organismes": "https://www.canada.ca/fr/gouvernement/min.html",
            "Premier ministre": "https://pm.gc.ca/fr",
            "Ministres": "https://www.canada.ca/fr/gouvernement/ministres.html",
            "Divulgation proactive": "https://ouvert.canada.ca/fr/divulgation-proactive",
            "Accès à l’information": "https://www.canada.ca/fr/secretariat-conseil-tresor/services/acces-information-protection-reseignements-personnels.html",
            "Projets de loi présentés au Parlement": "https://www.parl.ca/legisinfo/fr/legislation-en-bref"
          }
        },
        "Travailler au gouvernement": {
          url: "https://www.canada.ca/fr/gouvernement/fonctionpublique.html",
          submenus: {
            "mesures de précaution": "https://www.canada.ca/fr/gouvernement/systeme/gouvernement-numerique/securite-confidentialite-ligne/atteinte-vie-privee-systemes-bgrs-sirva-canada-touchant-personnel-actuel-ancien-gouvernement-federal.html",
            "Emplois au gouvernement du Canada": "https://www.canada.ca/fr/services/emplois/opportunites/gouvernement.html",
            "Rémunération, pension et avantages sociaux": "https://www.canada.ca/fr/gouvernement/fonctionpublique/remuneration.html",
            "Services et avantages sociaux du personnel militaire": "https://www.canada.ca/fr/gouvernement/fonctionpublique/avantagesmilitaires.html",
            "Services et avantages sociaux pour les membres de la GRC": "https://www.canada.ca/fr/gouvernement/fonctionpublique/avantagesgrc.html",
            "Dotation dans la fonction publique": "https://www.canada.ca/fr/gouvernement/fonctionpublique/dotation.html",
            "Apprentissage et perfectionnement": "https://www.canada.ca/fr/gouvernement/fonctionpublique/apprentissage.html",
            "Mieux-être, inclusion et diversité": "https://www.canada.ca/fr/gouvernement/fonctionpublique/mieux-etre-inclusion-diversite-fonction-publique.html",
            "Valeurs et éthique de la fonction publique": "https://www.canada.ca/fr/gouvernement/fonctionpublique/valeurs.html",
            "Innovation dans la fonction publique": "https://www.canada.ca/fr/gouvernement/fonctionpublique/modernisation.html",
            "Prix et reconnaissance": "https://www.canada.ca/fr/secretariat-conseil-tresor/services/innovation/prix-reconnaissance-evenements-speciaux.html"
          },
          mostRequested: {
            "Taux de rémunération": "https://www.canada.ca/fr/secretariat-conseil-tresor/sujets/remuneration.html#taux",
            "Travail hybride": "https://www.canada.ca/fr/gouvernement/fonctionpublique/modernisation/travail-hybride.html",
            "Négociations collectives": "https://www.canada.ca/fr/secretariat-conseil-tresor/services/conventions-collectives/negociations-collectives.html"
          }
        }
  };
