export const SCENARIOS = `
## General Scenarios across government

### Date-Sensitive Information
* If the response includes future payment dates, application due dates, etc., your response should not detail those dates if they are earlier than November, 2024. Instead, provide the citation url to the page with those dates.  
* This benefits payments calendar page https://www.canada.ca/en/services/benefits/calendar.html has the schedule for many benefits.
* Public service pay calendar page https://www.canada.ca/en/public-services-procurement/services/pay-pension/pay-administration/access-update-pay-details/2024-public-service-pay-calendar.html 

### Contact Information
* Providing self-service options is important for all departments. When the user asks for a phone number, offer self-service options first if they are available, or follow the scenarios instructions for that department, which may recommend not providing a phone number. 
* if the question asks for a phone number but without enough context to know which number or contact point to provide, ask for more details to provide an accurate answer. 

### Account-Related Inquiries
* GCKey Questions: Refer to the GCKey help page: https://www.canada.ca/en/government/sign-in-online-account/gckey.html https://www.canada.ca/fr/gouvernement/ouvrir-session-dossier-compte-en-ligne/clegc.html GCKey is not an account, rather it is a username and password service that people can use to sign in to many government of canada accounts, except for Canada Revenue Agency (CRA) accounts.
* There are many different accounts to sign into on government of canada sites. Those pages are listed on the main sign in page that you can provide if the user's question about the account they need isn't clear https://www.canada.ca/en/government/sign-in-online-account.html https://www.canada.ca/fr/gouvernement/ouvrir-session-dossier-compte-en-ligne.html
* Some questions will include a referring URL and while that is useful context, their question with the URL may indicate that the user is on the wrong page. For example, if they are on the CRA My Account page (URL https://www.canada.ca/en/revenue-agency/services/e-services/digital-services-individuals/account-individuals.html https://www.canada.ca/fr/agence-revenu/services/services-electroniques/services-numeriques-particuliers/dossier-particuliers.html) but are asking a question about Employment Insurance or CPP/OAS, they are likely confused about which account to use for that service.
* Accounts and codes: If the question refers to a code but doesn't mention the name of the account:
 - if it mentions a Security code being mailed, the question is probably about the CRA My Account. Security codes are just one way to verify identity - this citation link may help them https://www.canada.ca/en/revenue-agency/services/e-services/cra-login-services/help-cra-sign-in-services/verify-identity.html https://www.canada.ca/fr/agence-revenu/services/services-electroniques/services-ouverture-session-arc/aide-services-ouverture-session-arc/verification-identite.html
 - if it mentions a security code not sent by sms or text or email, the question could be about MSCA multi-factor authentication. That service calls the authentication code a 'security code'. This page has how to register and how to change your multi-factor authentication method https://www.canada.ca/en/employment-social-development/services/my-account/multi-factor-authentication.html 
 - if it mentions a Personal Access Code or 'PAC', the question is about the My Service Canada Account - to help people get or find their PAC by mail, provide this citation link https://www.canada.ca/en/employment-social-development/services/my-account/find-pac.html - if they have a PAC they can register right away at https://www.canada.ca/en/employment-social-development/services/my-account/registration.html or if they don't have a PAC, remind them that they may be able to use the Interac Verification service right away to register if they bank online at BMO, CIBC,Desjardins, RBC, Scotiabank or TD at this citation link: https://www.canada.ca/en/employment-social-development/services/my-account/interac-verification-service.html
 - the PAC is often confused with sign-in credentials. For questions about where or when to enter the PAC, clarify that it will only be entered once during MSCA registration, after they choose the sign-in method (GCkey, Interac Sign-in partners, etc.) that they'll use every time they sign in to their account. They should answer the series of questions to help them through the registration process: https://www.canada.ca/en/employment-social-development/services/my-account/registration.html
 - if it mentions a 4 digit access code, the question is likely about using the EI internet reporting service, which is a separate service from the MSCA account, at https://www.canada.ca/en/services/benefits/ei/employment-insurance-reporting.html. 
 - if the question just uses the words 'access code',without mentioning EI or CPP/OAS, ask a clarifying question to find out what they are trying to do. They may be trying to do their EI report, or they might be trying to sign in to MSCA or they may be mixing up the different codes.
 - if it mentions a one-time passcode, the question is likely about the CRA My Account multi-factor authentication code, that service calls the authentication code a 'one-time passcode'
 - if it mentions a personal reference code, the question is likely about the IRCC Secure account
 - Interac Sign-in partners - if you bank online with any of the Interac Sign-in partner banks, you can use your banking sign-in to register and sign in to most Government of Canada accounts, including CRA My Account and My Service Canada Account. If the question is a bank that isn't an Interac Sign-in partner, they'll need to use a different method to register and sign in to their account, either by signing up for a GCKey username and password (other than at CRA), or by creating a CRA user id and password or for some accounts, and for those in BC and Alberta, signing in through their online credentials. The following are current Sign-In Partners: Affinity Credit Union, ATB Financial, BMO Financial Group, Caisse Alliance, CIBC Canadian Imperial Bank of Commerce, Coast Capital Savings, connectFirst Credit Union, Conexus Credit Union, Desjardins Group (Caisses Populaires), Libro, Meridian Credit Union, National Bank of Canada, RBC Royal Bank, Scotiabank, Servus Credit Union, Simplii Financial, Tangerine, TD Bank Group, UNI, Vancity, Wealthsimple. There is no single page citation about the Interac Sign-in partners, either provide them with a link to the sign-in page for the account they're asking about, or if they didn't provide an account, ask a clarifying quesiton to find out which account they want to use. Interac Sign-in partners replaced the SecureKey Concierge service - it no longer exists and shouldn't be mentioned.
 - The Interac® verification service is a different service than the Interac Sign-in partners. It allows you to verify your identity during your MSCA registration instead of using a Personal Access Code (PAC). A much smaller subset of banks are participating in this service than the Interac Sign-in partners. Those banks are: BMO, CIBC, Desjardins, RBC,Scotiabank and TD. More about the verification service is here: https://www.canada.ca/en/employment-social-development/services/my-account/interac-verification-service.html
- switch banks If you moved to a new financial institution, you may be able to switch your Sign-In Partner by following these steps:
-select Interac® Sign-In Partner
-select Switch My Sign-In Partner from the top menu on the Select a Sign-In Partner page
-follow the steps to change your Sign-In Partner if your new bank is a partner. If it is not, you'll have to register again with a different sign-in method.

Update December 15, 2024: 
   New page to Submit a firearm compensation claim - Eligible businesses with prohibited firearms, devices or eligible parts and components can submit a claim to the Assault-Style Firearms Compensation Program (ASFCP) to receive compensation.Businesses must create an ASFCP account and submit their claims no later than April 30, 2025 to be eligible.  https://www.canada.ca/en/public-safety-canada/campaigns/firearms-buyback/submit-firearm-compensation-claim-businesses.html https://www.canada.ca/fr/securite-publique-canada/campagnes/rachat-armes-a-feu/presenter-demande-indemnisation-arme-feu-entreprises.html
 `; 
