/* eslint-disable no-unused-vars */
/* eslint-disable import/no-unused-modules */
import React from 'react';
import { GcdsContainer} from '@cdssnc/gcds-components-react';
import { GcdsHeader} from '@cdssnc/gcds-components-react';
import '@cdssnc/gcds-components-react/gcds.css';
import chatAppContainer from './components/chat/chatAppContainer';

function App() {
  const chatApp = <chatAppContainer />;
  return (
    <div className="App">
      <header>
      <GcdsHeader
  langHref="#"
  skipToHref="#"
>
<div slot="breadcrumb"><a href="https://www.canada.ca/en.html">Canada.ca</a></div>
</GcdsHeader>
   
      </header>
      <main>

      <GcdsContainer size="md" padding="400">
      <h1>AI Answers
      </h1>
  <h2>Get answers to your Canada.ca questions. </h2>
			<p class="small">To protect your privacy, names, numbers and addresses aren't accepted and will display as
				an <strong>X</strong>. Learn more
				at <a href="https://test.canada.ca/wayfinding-orientation-2023/ai/answers.html">About AI Answers</a>
			</p>
			<details>
				<summary>Terms of use</summary>
				<p>We may store your questions to improve system performance. Any
					personal information you enter will be deleted upon detection and won’t be retained.</p>
				<p> Responses generated by this AI system should not be considered as professional, legal, or medical
					advice. The information generated should be used at your own risk. We attempt to ensure the accuracy
					of the information provided but there is a possibility that the information may contain
					inaccuracies, and the information may not yet reflect recent changes or fulfill your particular
					needs or purposes. </p>
				<p>His Majesty the King in Right of Canada, as represented by the Minister of Agriculture and Agri-Food
					Canada, shall not be responsible for the content generated and/or any damages or consequences
					resulting from the use or misuse of the information provided through this conversation. You should
					always exercise your own judgement and seek professional advice before making any decisions based on
					the information provided. </p>
				<p>This AI system relies on information provided at the Canada.ca website and your use of this system
					and any information generated is also subject to the <a
						href="https://www.canada.ca/en/transparency/terms.html">Canada.ca Terms and conditions.</a> </p>
			</details>
        </GcdsContainer>
        <chatApp/>
      </main>
    </div>
  );
}

export default App;

