/* eslint-disable no-unused-vars */
/* eslint-disable import/no-unused-modules */
import React from 'react';
import TempChatAppContainer from './components/chat/TempChatAppContainer';
import { GcdsHeader, GcdsContainer, GcdsBreadcrumbs, GcdsBreadcrumbsItem, GcdsDetails, GcdsText, GcdsLink, GcdsFooter, GcdsTextarea } from '@cdssnc/gcds-components-react';

function App() {
  return (
    <>
      <GcdsHeader
        langHref="#"
        skipToHref="#">
        <GcdsBreadcrumbs slot="breadcrumb">
          <GcdsBreadcrumbsItem href="https://test.canada.ca/wayfinding-orientation-2023/ai/answered.html">AI</GcdsBreadcrumbsItem>
        </GcdsBreadcrumbs>
      </GcdsHeader>

      {/* <main> */}
      <GcdsContainer size="xl" mainContainer centered tag="main" className="mb-600">
        <h1 className='mb-400'>AI Answers</h1>
        <h2 className='mt-400 mb-400'>Get answers to your Canada.ca questions. </h2>

        <GcdsText className='mb-400'>To protect your privacy, names, numbers and addresses aren't accepted and will display as
          an <strong>X</strong>. </GcdsText>
        <GcdsText> AI can make mistakes - always use the link provided in your answer. Learn more
          at <a href="https://test.canada.ca/wayfinding-orientation-2023/ai/answers.html">About AI Answers</a>
        </GcdsText>
        <TempChatAppContainer />
      </GcdsContainer>
      <GcdsContainer size="sm" centered className="mb-600">
        <GcdsDetails detailsTitle='Privacy and AI terms of use' className='mb-400'>
          <GcdsText>
            We may store your questions to improve system performance. Any
            personal information you enter will be deleted upon detection and won't be stored.
          </GcdsText>
          <GcdsText>
            Use the Canada.ca link provided in the response to check your answer. Responses generated by this AI system should not be considered as professional, legal, or medical
            advice. The information generated should be used at your own risk. We attempt to ensure the accuracy
            of the information provided but there is a possibility that the information may contain
            inaccuracies, and the information may not yet reflect recent changes or fulfill your particular
            needs or purposes.
          </GcdsText>
          <GcdsText>
            This AI system relies on information provided at the Canada.ca website and your use of this system
            and any information generated is also subject to the <GcdsLink
              href="https://www.canada.ca/en/transparency/terms.html">Canada.ca Terms and conditions.</GcdsLink>
          </GcdsText>
        </GcdsDetails>
      </GcdsContainer>
      {/* </main> */}
      <GcdsFooter display='full'></GcdsFooter>
    </>
  );
}

export default App;