name: Deploy to OCI Container Instances

on:
  push:
    branches:
      - main
      - '**'

env:
  IMAGE_NAME: my-app
  IMAGE_TAG: ${{ github.sha }}
  OCIR_REPO: ${{ secrets.OCI_REPO }}
  COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
  SUBNET_OCID: ${{ secrets.OCI_SUBNET_OCID }}
  AVAILABILITY_DOMAIN: ca-toronto-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_CLI_USER }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_CLI_TENANCY }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_CLI_REGION }}" >> ~/.oci/config
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Log in to OCIR
        run: |
          echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login ${{ secrets.OCI_CLI_REGION }}.ocir.io -u ${{ secrets.OCI_CLI_TENANCY }}/${{ secrets.OCI_CLI_USER }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag and Push to OCIR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.OCI_CLI_REGION }}.ocir.io/${{ secrets.OCI_CLI_TENANCY }}/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.OCI_CLI_REGION }}.ocir.io/${{ secrets.OCI_CLI_TENANCY }}/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_CLI_USER }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_CLI_TENANCY }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_CLI_REGION }}" >> ~/.oci/config
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Deploy container
        run: |
          oci compute container-instance create \
            --compartment-id $COMPARTMENT_OCID \
            --display-name "${{ github.ref_name == 'main' && 'production-instance' || format('preview-{0}', github.ref_name) }}" \
            --availability-domain $AVAILABILITY_DOMAIN \
            --shape CI.Standard.E2.1 \
            --subnet-id $SUBNET_OCID \
            --containers '[{"imageUrl":"'"${{ secrets.OCI_CLI_REGION }}.ocir.io/${{ secrets.OCI_CLI_TENANCY }}/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG"'"}]'
