name: Deploy to OCI Container Instances

on:
  push:
    branches:
      - main
      - '**'

env:
  IMAGE_NAME: ai-answers
  IMAGE_TAG: latest
  OCIR_REPO: ${{ secrets.OCI_REPO }}
  COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
  SUBNET_OCID: ${{ secrets.OCI_SUBNET_OCID }}
  AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAIL_DOMAIN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Login to OCIR
        run: |
          echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login ${{ secrets.OCI_CLI_REGION }}.ocir.io -u "${{ secrets.OCI_REPO }}/${{ secrets.OCI_CLI_USER }}" --password-stdin
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag and Push to OCIR
        run: |
          docker tag "$IMAGE_NAME:$IMAGE_TAG" "${{ secrets.OCI_CLI_REGION }}.ocir.io/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG"
          docker push ${{ secrets.OCI_CLI_REGION }}.ocir.io/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG
     
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set display name
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "DISPLAY_NAME=production-instance" >> $GITHUB_ENV
          else
            echo "DISPLAY_NAME=preview-${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Deploy container
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: |
            compute container-instance create \
              --compartment-id $OCI_COMPARTMENT_OCID \
              --display-name $DISPLAY_NAME \
              --availability-domain $OCI_AVAIL_DOMAIN \
              --shape CI.Standard.E2.1 \
              --subnet-id $OCI_SUBNET_OCID \
              --containers '[{"imageUrl":"'"${{ secrets.OCI_CLI_REGION }}.ocir.io/${{ secrets.OCI_CLI_TENANCY }}/$OCIR_REPO/$IMAGE_NAME:$IMAGE_TAG"'"}]'
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}